# Global parameters
[global]
	workgroup = BOTTLEMGR
	realm = BOTTLEMGR.LOCALNET
	netbios name = ND1
	server role = active directory domain controller
	dns forwarder = 172.18.32.1

	bind interfaces only = yes
	interfaces = 127.0.0.1/8 172.18.32.159/24
        idmap_ldb:use rfc2307 = yes

        passdb backend = samba4

        unix charset = UTF-8
        dos charset = CP932

	log level = 0
        max log size = 5

        time server = Yes
        printing = bsd
        load printers = no
        winbind separator = /
        winbind use default domain = yes

        browseable = No

        create mask = 0664
        directory mask = 0775

	oplocks = No
	blocking locks = No

[netlogon]
	path = /usr/local/samba4/var/locks/sysvol/nd.localnet/scripts
	read only = No

[sysvol]
	path = /usr/local/samba4/var/locks/sysvol
	read only = No

[share]
        comment ="Share"
        path = /home/adpc/share
        read only = No
        browseable = Yes

	locking = No
	strict locking = No

[report]
        comment ="Report"
        path = /home/adpc/report
        read only = No
        browseable = Yes

